services:
  - type: web
    name: kaspa-raffle
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DRAW_ENABLED
        value: "false"
      - key: POLL_MS
        value: "30000"
      - key: NODE_VERSION
        value: "20"
      - key: RAFFLE_ADDRESS
        value: winraffle.kas
      - key: RAFFLE_DISPLAY_ADDRESS
        value: winraffle.kas
      - key: RAFFLE_ONCHAIN_FALLBACK
        value: kaspa:qr3rxmae6r5h9kkt7q5my7rajy492da7cxpy0kkzr99tk3xcydc2uwa3a7u6r